### ISSUE TITLE
wrong language: usb-key-live-install.html

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#12]
Some pages are mostly in french and should not be under the english folder: Or maybe leave it empty just as a placeholder something like: 

## translation in progress.....

---

*  [usb-key-live-install.html](https://github.com/NuTyX/houaphan/blob/master/www/en/usb-key-live-install.html) 
* [bash-basics.html](https://github.com/NuTyX/houaphan/blob/master/www/en/bash-basics.html)

**Comment by tnut** [comment]
you right, but as you can see (or let say in this case not see) this article is not available neither on the french part. As it it obsolete and never had the chance to upgrade it

**Comment by peter1000** [comment]
Maybe one solution would be to have in the meantime just a placeholder:

# Under cunstruction

----

**Comment by tnut** [comment]
I just look at it, this article was for the installation of a live version of NuTyX. In IMO, it could be delete. It's not 'houaphan' applicable anymore as we don't have a live version anymore

**Comment by peter1000** [comment]
BTW: just  some question as I try to decide if *NuTyX* might be an option for me or to look into Crux.

I have been running: Gentoo, Ubuntu and currently Arch linux. 

Looking for something without: 'systemd' and as I have special needs to compile everything from source.

Crux looks like a good option but also NuTyX (eventhough the is not much documentation)

In your opinion how does 'Crux' and 'NuTyX' differ for someone who needs to compile anyway all from source?

Thanks a lot
P

**Comment by peter1000** [comment]
Do you speak 'german too' ?

**Comment by tnut** [comment]
I would be please to say, use NuTyX as I do since almost 10 years now but I guess I would need some arguments: 
- Even if primary idea is to have binaries base distro, we have to admit that we are only a few people maintaining the packages. For this reason the packager manager IMO is a central peace of code (or tool). For almost 8 years I was using pkgutils tool as it is in CRUX today, but I really felt the need to make or own once which I did now. So Just imagine that cards is doing what pkgutils, prt-get, pkg-get and ports applications in CRUX does but under on single roof.
- The big benefit I think with NuTyX is the installation script, the runtime dependencies found automatically, the collection and the meaning behind them. 

For the documentation, as you can imagine nobody is interrested to maintain it. So I do it all on my own and that OK so. 

For the german, I do speak but not that good ( I work in a swiss german compagny )

**Comment by peter1000** [comment]
Thanks, I guess I will give *NuTyX* a try and see how it goes. If you want I send you some pull requests with issues I find ;)

**Comment by tnut** [comment]
I appreciate your interest
